source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

link_with 'Underdark', 'UnderdarkTests'

pod 'ProtocolBuffers', '1.9.9.2' # From https://github.com/alexeyxo/protobuf-objc
pod 'MSWeakTimer', '1.1.0'
