source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

use_frameworks!
inhibit_all_warnings!

target 'UDApp' do

# Underdark requirements:
pod 'ProtocolBuffers', '1.9.9' # From https://github.com/alexeyxo/protobuf-objc
pod 'MSWeakTimer', '1.1.0'

pod 'CocoaLumberjack/Swift'

end