// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Packet;
@class PacketBuilder;
@class SyncPacket;
@class SyncPacketBuilder;



@interface PacketsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Packet_packetId @"packetId"
#define Packet_kind @"kind"
#define Packet_nodeId @"nodeId"
#define Packet_age @"age"
#define Packet_payload @"payload"
@interface Packet : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPacketId_:1;
  BOOL hasNodeId_:1;
  BOOL hasAge_:1;
  BOOL hasKind_:1;
  BOOL hasPayload_:1;
  SInt64 packetId;
  SInt64 nodeId;
  SInt64 age;
  SInt32 kind;
  NSData* payload;
}
- (BOOL) hasPacketId;
- (BOOL) hasKind;
- (BOOL) hasNodeId;
- (BOOL) hasAge;
- (BOOL) hasPayload;
@property (readonly) SInt64 packetId;
@property (readonly) SInt32 kind;
@property (readonly) SInt64 nodeId;
@property (readonly) SInt64 age;
@property (readonly, strong) NSData* payload;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PacketBuilder*) builder;
+ (PacketBuilder*) builder;
+ (PacketBuilder*) builderWithPrototype:(Packet*) prototype;
- (PacketBuilder*) toBuilder;

+ (Packet*) parseFromData:(NSData*) data;
+ (Packet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Packet*) parseFromInputStream:(NSInputStream*) input;
+ (Packet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Packet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Packet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PacketBuilder : PBGeneratedMessageBuilder {
@private
  Packet* resultPacket;
}

- (Packet*) defaultInstance;

- (PacketBuilder*) clear;
- (PacketBuilder*) clone;

- (Packet*) build;
- (Packet*) buildPartial;

- (PacketBuilder*) mergeFrom:(Packet*) other;
- (PacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPacketId;
- (SInt64) packetId;
- (PacketBuilder*) setPacketId:(SInt64) value;
- (PacketBuilder*) clearPacketId;

- (BOOL) hasKind;
- (SInt32) kind;
- (PacketBuilder*) setKind:(SInt32) value;
- (PacketBuilder*) clearKind;

- (BOOL) hasNodeId;
- (SInt64) nodeId;
- (PacketBuilder*) setNodeId:(SInt64) value;
- (PacketBuilder*) clearNodeId;

- (BOOL) hasAge;
- (SInt64) age;
- (PacketBuilder*) setAge:(SInt64) value;
- (PacketBuilder*) clearAge;

- (BOOL) hasPayload;
- (NSData*) payload;
- (PacketBuilder*) setPayload:(NSData*) value;
- (PacketBuilder*) clearPayload;
@end

#define SyncPacket_packetIds @"packetIds"
@interface SyncPacket : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  PBAppendableArray * packetIdsArray;
}
@property (readonly, strong) PBArray * packetIds;
- (SInt64)packetIdsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SyncPacketBuilder*) builder;
+ (SyncPacketBuilder*) builder;
+ (SyncPacketBuilder*) builderWithPrototype:(SyncPacket*) prototype;
- (SyncPacketBuilder*) toBuilder;

+ (SyncPacket*) parseFromData:(NSData*) data;
+ (SyncPacket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncPacket*) parseFromInputStream:(NSInputStream*) input;
+ (SyncPacket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncPacket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SyncPacket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SyncPacketBuilder : PBGeneratedMessageBuilder {
@private
  SyncPacket* resultSyncPacket;
}

- (SyncPacket*) defaultInstance;

- (SyncPacketBuilder*) clear;
- (SyncPacketBuilder*) clone;

- (SyncPacket*) build;
- (SyncPacket*) buildPartial;

- (SyncPacketBuilder*) mergeFrom:(SyncPacket*) other;
- (SyncPacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SyncPacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)packetIds;
- (SInt64)packetIdsAtIndex:(NSUInteger)index;
- (SyncPacketBuilder *)addPacketIds:(SInt64)value;
- (SyncPacketBuilder *)setPacketIdsArray:(NSArray *)array;
- (SyncPacketBuilder *)setPacketIdsValues:(const SInt64 *)values count:(NSUInteger)count;
- (SyncPacketBuilder *)clearPacketIds;
@end


// @@protoc_insertion_point(global_scope)
